import { JSONSchemaType } from 'ajv'
import { BlockParameters } from '../../../types'

export interface Speech2TextParams {
  audio: string
  model: string
  transcription: string
  translate: boolean
  language: string
}

export const speech2TextParams: BlockParameters = {
  model: {},
  schema: {
    type: 'object',
    properties: {
      model: {
        type: 'string',
        title: 'Model',
        default: 'large-v2',
        enum: ['large-v2', 'large'],
        uniforms: {
          help: 'Some explanation of what this parameter actually does',
        },
      },
      transcription: {
        type: 'string',
        title: 'Transcription',
        default: 'plain text',
        enum: ['plain text', 'srt', 'vtt'],
        uniforms: {
          help: 'Some explanation of what this parameter actually does',
        },
      },
      translate: {
        type: 'boolean',
        title: 'Translate',
        default: false,
        uniforms: {
          help: 'Some explanation of what this parameter actually does',
        },
      },
      language: {
        type: 'string',
        title: 'Language',
        default: 'en',
        enum: [
          'af',
          'am',
          'ar',
          'as',
          'az',
          'ba',
          'be',
          'bg',
          'bn',
          'bo',
          'br',
          'bs',
          'ca',
          'cs',
          'cy',
          'da',
          'de',
          'el',
          'en',
          'es',
          'et',
          'eu',
          'fa',
          'fi',
          'fo',
          'fr',
          'gl',
          'gu',
          'ha',
          'haw',
          'he',
          'hi',
          'hr',
          'ht',
          'hu',
          'hy',
          'id',
          'is',
          'it',
          'ja',
          'jw',
          'ka',
          'kk',
          'km',
          'kn',
          'ko',
          'la',
          'lb',
          'ln',
          'lo',
          'lt',
          'lv',
          'mg',
          'mi',
          'mk',
          'ml',
          'mn',
          'mr',
          'ms',
          'mt',
          'my',
          'ne',
          'nl',
          'nn',
          'no',
          'oc',
          'pa',
          'pl',
          'ps',
          'pt',
          'ro',
          'ru',
          'sa',
          'sd',
          'si',
          'sk',
          'sl',
          'sn',
          'so',
          'sq',
          'sr',
          'su',
          'sv',
          'sw',
          'ta',
          'te',
          'tg',
          'th',
          'tk',
          'tl',
          'tr',
          'tt',
          'uk',
          'ur',
          'uz',
          'vi',
          'yi',
          'yo',
          'zh',
        ],
        uniforms: {
          help: 'Some explanation of what this parameter actually does',
        },
      },
    },
    required: ['model', 'transcription', 'translate', 'language'],
  } as JSONSchemaType<Omit<Speech2TextParams, 'audio'>>,
}
